# Generated by Django 2.2.5 on 2020-04-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='editor',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='sheet',
            name='nb_instruments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='duration',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
